version: '3.4'

services:
  zookeeper:
    image: confluentinc/cp-zookeeper:latest
    environment:
      ZOOKEEPER_CLIENT_PORT: 2181
      ZOOKEEPER_TICK_TIME: 2000
    ports:
      - 2181:2181

  kafka:
    image: confluentinc/cp-kafka:latest
    hostname : broker
    depends_on:
      - zookeeper
    ports:
      - 9092:9092
    environment:
      KAFKA_BROKER_ID: 1
      KAFKA_ZOOKEEPER_CONNECT: 'zookeeper:2181'
      KAFKA_ADVERTISED_LISTENERS : PLAINTEXT://kafka:29092,PLAINTEXT_HOST://localhost:9092
      KAFKA_LISTENER_SECURITY_PROTOCOL_MAP: PLAINTEXT:PLAINTEXT,PLAINTEXT_HOST:PLAINTEXT
  logstash:
    image : docker.elastic.co/logstash/logstash:8.4.1

#kafka-topics --create --bootstrap-server localhost:29092 --replication-factor 1 --partitions 1 --topic test_kafka
#kafka-console-producer --broker-list localhost:29092 --topic test_kafka
#kafka-console-consumer --bootstrap-server localhost:29092 --topic test_kafka --from-beginning --partition 0
# logstash -f /usr/share/logstash/pipeline/logstash.conf
# rm -rf .lock
#KAFKA_ADVERTISED_LISTENERS : PLAINTEXT://broker:29092,PLAINTEXT_HOST://localhost:9092
#KAFKA_LISTENER_SECURITY_PROTOCOL_MAP: PLAINTEXT:PLAINTEXT,PLAINTEXT_HOST:PLAINTEXT 
#docker cp docker cp C:\Users\elbaraka\Desktop\logstash.conf  docker_testing-logstash-1:/usr/share/logstash/pipeline/logstash.conf